version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perfectfit
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    image: ghcr.io/johnthebelovedcoder/perfectfit-api:latest
    pull_policy: always
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      CLOUDINARY_API_KEY: 447985788567659
      CLOUDINARY_API_SECRET: 7mEKY3TjR5hhZeUEQckGZsNpca4
      CLOUDINARY_CLOUD_NAME: dbzbeaxfm
      CLOUDINARY_UPLOAD_PRESET: ml_default
      DATABASE_URL: postgresql://perfectfit:oAgkKRWyRjMM8DY91L5L8IGuttol4X6D@dpg-d8sfg177f7vs73cso880-a/perfectfit_93bl
      DIRECT_URL: postgresql://perfectfit:oAgkKRWyRjMM8DY91L5L8IGuttol4X6D@dpg-d8sfg177f7vs73cso880-a/perfectfit_93bl
      FIELD_ENCRYPTION_KEY: 3d42fd980abd448ce4c758de435514019ba1658499f7c155f4f3b28937d2b301
      JWT_REFRESH_SECRET: "sn/EZvCcuEFqY8KtAcDsOsWtqxDLiHiRTX0jrhB2e9Q="
      JWT_SECRET: "zJ6AgBCDn8Kb/ZaP0SzBuaLce48AeuLRkz34xw3HZoM="
      NEXT_PUBLIC_ADMIN_URL: https://perfectfit-admin.onrender.com
      NEXT_PUBLIC_SELLER_URL: https://perfectfit-seller.onrender.com
      NEXT_PUBLIC_STOREFRONT_URL: https://perfectfit-storefront.onrender.com
      NODE_ENV: production
      REDIS_URL: redis://red-d8sfg177f7vs73cso84g:6379
      RESEND_API_KEY: re_Gjoyemh5_Ng4NgxpNjmZtTHMfDseqBnC3
      STRIPE_SECRET_KEY: sk_test_51TlACQ…00vDcOZ1vu
      STRIPE_WEBHOOK_SECRET: whsec_dummy
      THREAD_WAREHOUSE_ADDRESS: "1 Warehouse Way, Tulsa, Oklahoma"
      THREAD_WAREHOUSE_CONTACT_NUMBER: "+1 (973) 282-6945"
    command: sh -c "until nc -z postgres 5432; do echo 'Waiting for postgres...'; sleep 1; done; pnpm --filter @thread/database exec prisma db push && node dist/main"

  storefront:
    image: ghcr.io/johnthebelovedcoder/perfectfit-storefront:latest
    pull_policy: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: https://perfectfit-api-hive.onrender.com
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dbzbeaxfm

  seller:
    image: ghcr.io/johnthebelovedcoder/perfectfit-seller:latest
    pull_policy: always
    depends_on:
      - api
    ports:
      - "3002:3002"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3002
      NEXT_PUBLIC_API_URL: https://perfectfit-api-hive.onrender.com
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dbzbeaxfm

  admin:
    image: ghcr.io/johnthebelovedcoder/perfectfit-admin:latest
    pull_policy: always
    depends_on:
      - api
    ports:
      - "3003:3003"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3003
      NEXT_PUBLIC_API_URL: https://perfectfit-api-hive.onrender.com
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dbzbeaxfm

volumes:
  postgres-data:
